export interface QuanTriVanBanDi {
    soKiHieu?: string,
    trichYeu?: string,
    soDi?: number,
    ngayBanHanh?: string,
    loaiVBNghiepVu?: string,
    trangThai?: string,
    trangThaiGui?: string,
    dieuKienGui?: string,
    coQuanBh?: string,
    maDinhDanhVB?: string,
    mucDo?: string,
    noiNhanGui?: string,
    soDiDen?: number,
    soDiDenCustom?: string,
    tenLoaiVb?: string,
    tenSoVB?: string,
    ngayNhanGui?: string,
    soBanPhatHanh?: number,
    soHienTai?: string,
}

export interface TimKiemVBDi {
    keyWord?: string,
    soKyHieu?: string,
    nam?: number,
    thang?: number,
    timChinhXac?: number,
    ngayBanHanh?: string,
    ngayGui?: string,
    trichYeu?: string,
    trangThai?: number,
    mucDo?: number,
    soDi?: number,
    soVanBanId?: number,
    donViId?: number,
    loaiVanBanId?: number,
    vanBanId?: number,
}
